### ISSUE TITLE
Add UI Component

### ISSUE THREAD

**Issue by Potential17** [Potential17/web-scraping#2]
User will be able to scraped data from imdb's website.

UI will consist of the following - 

1.  A search bar
2.  Feature of pagination

**Comment by coldkillerr** [comment]
> User will be able to scraped data from imdb's website.
> 
> UI will consist of the following -
> 
>     1. A search bar
> 
>     2. Feature of pagination

Hey! If this is not assigned to any I can do this !

**Comment by g-bhagwanani** [comment]
Hey @Potential17 I can work on this, we can create a backend server using Flask, and connect it with React on the frontend.

**Comment by coldkillerr** [comment]
> Hey @Potential17 I can work on this, we can create a backend server using Flask, and connect it with React on the frontend.

Hey @g-bhagwanani  is there a way I can contact you ? So that we can discuss this ?

**Comment by g-bhagwanani** [comment]
> > Hey @Potential17 I can work on this, we can create a backend server using Flask, and connect it with React on the frontend.
> 
> Hey @g-bhagwanani is there a way I can contact you ? So that we can discuss this ?

Sure @coldkillerr, can you ping me on telegram? https://t.me/bhagw_an
